---

- hosts: all
  become: true
  tasks:

  - name: update repository index and install apache2 and php packages for Ubuntu/Debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: update repo index and install apache2 and php packages for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
